### ISSUE TITLE
Unable to load selenium from system or Sublime Text, missing dep

### ISSUE THREAD

**Issue by kgizdov** [memoryleak/TerraformSnippets-AWS#1]
As in the title. I have `selenium` installed on the system, which is `Arch Linux x86_64` with `Python 3.9.6`.

```python
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 312, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 808, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gizdov/.config/sublime-text/Packages/TerraformSnippets-AWS/Scraper.py", line 1, in <module>
    from selenium import webdriver
ImportError: cannot import name 'webdriver' from 'selenium' (unknown location)
reloading plugin TerraformSnippets-AWS.Terraform
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 312, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 808, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gizdov/.config/sublime-text/Packages/TerraformSnippets-AWS/Terraform.py", line 1, in <module>
    from selenium.webdriver.firefox.webdriver import WebDriver
ModuleNotFoundError: No module named 'selenium.webdriver'
```

**Comment by memoryleak** [comment]
@kgizdov How did you install the package? Are you trying to use the package or generate new snippets?

**Comment by kgizdov** [comment]
I installed it using `PackageControl` and I'm just trying to use it.
